models/message_board.py
from models import Model
from models.mongodb import MongoDB
import time
from flask import (
    request,
    flash,
)
from models.user import (
    current_user_name,
    User,
)
from tools import (
    strftime,
    log,
)
import json
import urllib.request
import os


class MessageBoard(MongoDB, Model):
    def __init__(self, form):
        self.id = None
        self.content = form.get('content', '')
        self.ct = int(time.time())
        self.ut = self.ct
        self.cookie = request.cookies.get('cookie')
        self.message_user = form.get('user', '')
        self.user = None
        self.delete = False

    @classmethod
    def new_without_save(cls, form):
        """
        将表单数据传入类，
        在__init__()变成类属性
        """
        t = cls(form)

        # 加入加户标记
        username = current_user_name()
        t.user = username
        return t

    @classmethod
    def all_user(cls):
        """返回所有用户的用户，包含Message库与User库"""
        # 非注册用户
        all_list = cls.all()
        data_by_message_user = [c.message_user for c in all_list]
        # 注册同户
        register_list = User.all()
        register = [u.username for u in register_list]
        all_user_list = data_by_message_user + register
        return all_user_list

    @classmethod
    def all_msg_include_del(cls):
        ms = cls.all()
        return ms

    @classmethod
    def all_message(cls):
        """返回所留言数据"""
        all_list = cls.all()
        data = []
        # 转换时间格式
        for l in all_list:
            if l.delete is False:
                l.ct = strftime(l.ct)
                data.append(l)
        return data

    @classmethod
    def delete(cls, id):
        print('delete', id)
        m = cls.find_by(id=int(id))
        if current_user_name() == m.user and current_user_name() is not None:
            # print("wtffffffffff", current_user_name(), m.user)
            m.delete = True
            m.save()
            log(f'{m.user} 删除了\n{m.content}')
        elif request.cookies.get('cookie') == m.cookie and m.user is None:
            # # _________________________
            # print(request.cookies.get('cookie'))
            # print(m.cookie)
            m.delete = True
            m.save()
            log(f'{m.cookie} 删除了\n{m.content}')
        else:
            flash("你不能删除别人的内容，或你的身份已经过期")
            return {'flash': '你不能删除别人的内容，或你的身份已经过期'}
        return m


def guest(form):
    m = MessageBoard.new_without_save(form)
    # 第一次之后就不用输临时用户名，则m.message为空,此时要指定旧数据中的用户名给它
    if m.message_user is '':
        m.message_user = MessageBoard.find_by(cookie=request.cookies.get('cookie')).message_user
    # print(m.content, type(m.content), len(m.content))
    # if m.content != ' ' and len(m.content) != 0:
    #     m.save()
    # 用于第一次输入临时用户名找到是否存在cookie，有值就表名用户名重复了
    check_cookie = MessageBoard.find_by(message_user=m.message_user).cookie
    return m, check_cookie


class CityCode(object):
    _city_code = None

    def __new__(cls):
        if cls._city_code is None:
            path = os.path.join(os.getcwd(), 'data', 'city')
            with open(path, 'r', encoding='utf-8') as f:
                d = json.load(f)
                cls._city_code = d
        return cls._city_code

    @classmethod
    def city_to_code(cls, addr):
        city = addr['city_addr']
        code = cls._city_code[city]
        return code

    @staticmethod
    def get_weather_data(url):
        response = urllib.request.urlopen(url)
        r = response.read().decode('utf-8')
        d = json.loads(r)['value'][0]
        g = [i for i in d['indexes'] if i['abbreviation'] == 'gm'][0]
        w = d["weathers"][0]
        city = {'city': d['city']}
        pm25 = {
            "aqi": d['pm25']['aqi'],
            'cityrank': d['pm25']['cityrank'],
            'pm10': d['pm25']['pm10'],
            'pm25': d['pm25']['pm25'],
            'quality': d['pm25']['quality'],
        }
        gm = {'content': g['content']}
        weather = {
            'temp_day_c': w['temp_day_c'],
            "temp_night_c": w["temp_night_c"],
            'weather': w['weather'],
        }
        data = {
            'pm25': pm25,
            'gm': gm,
            'weather': weather,
            'city': city,
        }
        return data

models/todo.py
from models import Model
import time
from flask import request
from tools import (
    strftime,
    log,
)
from models.user import (
    current_user_name,
)
from models.mongodb import MongoDB


class Todo(MongoDB, Model):
    def __init__(self, form):
        self.id = None
        self.title = form.get('title', '')
        self.complete = False
        # 创建时间，更新时间
        self.ct = int(time.time())
        self.ut = self.ct
        self.cookie = request.cookies.get('cookie')
        self.user = None

    @classmethod
    def new(cls, form):
        """
        创建并保存一个todo,保存于Todo.txt
        :param form: todo字典,如{'title':'doing'}
        :return: todo实例
        """
        t = cls(form)
        t.save()
        return t

    @classmethod
    def new_without_save(cls, form):
        """
        将表单数据传入Todo类，
        在__init__()变成类属性
        """
        t = cls(form)
        # 加入加户标记
        username = current_user_name()
        t.user = username

        return t

    @classmethod
    def update(cls, id, form):
        """更新todo"""
        t = cls.find(id)
        valid_names = [
            'title',
            'completed',
        ]
        for key in form:
            if key in valid_names:
                # 更新为form中的数据
                setattr(t, key, form[key])
        t.save()
        return t

    @classmethod
    def complete(cls, id, completed=True):
        """"""
        t = cls.find(id)
        t.complete = completed
        t.save()
        return t

    @classmethod
    def all_by_cookie(cls):
        """从所有todo中返回属于请求cookie的数据"""
        all_list = cls.all()
        data_by_cookie = []
        for l in all_list:
            if l.cookie == request.cookies.get('cookie'):
                # 时间格式转换
                l.ct = strftime(l.ct)
                data_by_cookie.append(l)
        return data_by_cookie

    @classmethod
    def id_for_cookie(cls, todo_id):
        """返回所在的id的cookie值"""
        models = cls.all()
        for m in models:
            # print(m)
            if m.id == todo_id:
                return m.cookie

    @staticmethod
    def user_in_todo(user):
        """
        传入用户对象
        为todo加入当前登陆用户属性
        """
        cookie = request.cookies.get('cookie')
        todos = Todo.find_all(cookie=cookie)
        log('user in todo', todos)
        if len(todos) >= 1:
            for t in todos:
                # 只有t.user为空时才能加入，
                # 避免重复注册导致数据迁移
                if t.user is None:
                    t.user = user.username
                    t.save()

    @classmethod
    def all_by_user(cls):
        """从所有todo中返回属于请求cookie的数据"""
        all_list = cls.all()
        data_by_cookie = []

        for l in all_list:
            if l.user == current_user_name():
                # 时间格式转换
                l.ct = strftime(l.ct)
                data_by_cookie.append(l)
        return data_by_cookie

    # @classmethod
    # def id_for_user(cls, username):
    #     """返回所在的id的cookie值"""
    #     models = cls.all()
    #     for m in models:
    #         # print(m)
    #         if m.username == username:
    #             return m.username

# if __name__ == '__main__':
#     print('text')

routes/message_board.py
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    flash,
    abort,
)
from models.message_board import (
    MessageBoard,
    guest,
    CityCode,
)
from models.user import (
    current_user_name,
    set_salt_cookie,
)
from tools import log
from flask_socketio import SocketIO, emit

socketio = SocketIO()
main = Blueprint('message', __name__)


@main.route('/')
def index():
    username = current_user_name()
    all_message = MessageBoard.all_message()
    cookie = request.cookies.get('cookie')
    guest = MessageBoard.find_by(cookie=cookie).message_user
    template = render_template(
        'message_board.html',
        title="聊天室",
        username=username,
        message=all_message,
        guest=guest,
        none=None,
        ip=request.remote_addr,
    )
    r = set_salt_cookie(template)
    return r


@main.route('/add', methods=['post'])
def add():
    form = request.form
    # print(form, "testttt")
    m, check_cookie = guest(form)
    all_user = MessageBoard.all_user()
    # 判断内容是否空白
    if m.content == ' ' or len(m.content) == 0:
        flash("你说得很空白无力")
    # 排除重名
    elif m.message_user is '' and m.user is None:
        flash("给自己一个好听的昵称吧")
    # 查看cookie是否匹配
    elif (check_cookie is not '' or check_cookie is not None) \
            and check_cookie != request.cookies.get('cookie') \
            and m.message_user in all_user \
            and m.user is None:
        flash("好名字都被别人取了，再想一个昵称吧")
    else:
        m.save()
        log('save', form)
    return redirect(url_for('.index'))


@main.route('/delete/<id>')
def delete(id):
    MessageBoard.delete(id)
    return redirect(url_for(".index"))


# 连接之后返回所有聊天信息
@socketio.on('connect_event', namespace='/chat')
def connected_msg(msg):
    log("来自客户端的：", msg)
    all_message = MessageBoard.all_message()
    dict_ = {}
    [dict_.update({n: m.__dict__}) for n, m in enumerate(all_message)]
    for d in dict_.values():
        del d['cookie'], d["_id"], d['delete']
    # print(len(all_message))
    # print(json.dumps(dict_))
    emit('server_response', {'data': dict_})


# 聊天信息的接收与响应
@socketio.on('client_event', namespace='/chat')
def connected_msg(form):
    log("来自客户端的：", form)
    m, check_cookie = guest(form)
    all_user = MessageBoard.all_user()
    # 判断内容是否空白
    if m.content == ' ' or len(m.content) == 0:
        emit('flash_message', {'flash': "你说得很空白无力"})
    # 排除重名
    elif m.message_user is '' and m.user is None:
        emit('flash_message', {'flash': "给自己一个好听的昵称吧"})
    # 查看cookie是否匹配
    elif (check_cookie is not '' or check_cookie is not None) \
            and check_cookie != request.cookies.get('cookie') \
            and m.message_user in all_user \
            and m.user is None:
        emit('flash_message', {'flash': "好名字都被别人取了，再想一个昵称吧"})
    else:
        m.save()
        print('save')
    # return redirect(url_for('.index'))
        emit('new_message', {
            'user': m.user,
            'message_user': m.message_user,
            'id': m.id,
            'ct': m.ct,
            'content': m.content,
        },
             broadcast=True,
             )


# 删除
@socketio.on('delete_msg', namespace='/chat')
def delete_msg(msg):
    log("尝试删除", msg)
    m_id = msg['id']
    m = MessageBoard.delete(m_id)
    if type(m) == dict:
        emit('flash_message', m)
    else:
        emit('remove', {'id': m.id}, broadcast=True)


# 天气
@socketio.on('city_addr', namespace='/chat')
def get_weather(addr):
    log(addr, ':', request.cookies.get('cookie'))
    single_instanse = CityCode()
    code = CityCode.city_to_code(addr)
    url = f"http://aider.meizu.com/app/weather/listWeather?cityIds={code}"
    # print(url)
    data = CityCode.get_weather_data(url)
    emit('weather', {'data': data})


# 超级用户接口
@main.route('/all/<int:p>')
def all_msg(p):
    username = current_user_name()
    if username != 'yan':
        abort(404)
    ms = list(reversed(MessageBoard.all_msg_include_del()))
    len_all = len(ms)
    len_del = MessageBoard.find(delete=True).count()
    page_n = (len_all//20)+2
    page = ms[20*(p-1): 20*p]
    return render_template(
        'all_by_yan.html',
        length=page_n,
        page=page,
        title="Yan",
        username=username,
        len_del=len_del,
        len_all=len_all,
        )


if __name__ == '__main__':
    import json
    with open('../data/city', 'r', encoding='utf-8') as f:
        d = json.load(f)
    print(d)

routes/todo.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    request,
    url_for,
    make_response,
    flash,
    jsonify,
)
from models.todo import Todo
from tools import (
    log,
    strftime,
)
from models.user import (
    salt,
    current_user_name,
)


# 创建蓝图,蓝图名为main
main = Blueprint('todo', __name__)


@main.route('/')
def index():
    # 游客数据用cookie。
    if current_user_name() is None:
        todo_list = Todo.all_by_cookie()
    # 用户数据优于session，用户优先
    else:
        todo_list = Todo.all_by_user()

    username = current_user_name()
    template = render_template('todo.html', todos=todo_list, title='Todo', username=username)
    r = make_response(template)
    if request.cookies.get('cookie') is None:
        r.set_cookie('cookie', salt(), max_age=2419200)
    return r


@main.route('/add', methods=['post'])
def add():
    if request.method == 'POST' or request.method == 'post':
        form = request.json
        if form is None:
            form = request.form
    print(form)
    t = Todo.new_without_save(form)

    if t.title == ' ' or len(t.title) == 0:
        # flash("人生在世总是要干点什么的")
        return jsonify({'flash': "人生在世总是要干点什么的"})
    else:
        t.save()
    # return redirect(url_for('todo.index'))
    return jsonify({
        "id": t.id,
        "ct": strftime(t.ct),
        "title": t.title,
        "status": 200,
    })


@main.route('/delete/<int:todo_id>')
def delete(todo_id):
    log("tying delete id---", todo_id)
    u_name = current_user_name()
    t = Todo.find_by(id=todo_id)
    # 用户身份删除
    if u_name is not None and t.user == u_name:
        Todo.delete(todo_id)
    # 游客身份删除
    elif t is not None and t.cookie == request.cookies.get('cookie'):
        # 游客不能删除已注册给用户的数据
        if t.user is None:
            Todo.delete(todo_id)
            log("deleted id:", todo_id)
        else:
            return jsonify({"flash": "离线状态不能删除在登陆状态时所添加的数据"})
    else:
        return jsonify({"flash": "你要删除火星上面的东西吗"})
    return jsonify({
        'id': t.id,
        'title': t.title,
        'status': 200,
    })

routes/user.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    request,
    url_for,
    make_response,
    flash,
    session,
)
from tools import log
from models.user import (
    User,
    current_user,
    current_user_name,
)
from models.todo import Todo

# 创建蓝图,蓝图名为main
main = Blueprint('user', __name__)


@main.route('/login')
def login():
    user = current_user()
    if user is not None:
        username = user.username
    else:
        username = None
    return render_template('login.html', title='login', username=username)


@main.route('/login/in', methods=['post'])
def sign_in():
    form = request.form
    # log('login form', form)
    u = User.verify_user(form)
    # log('u', u)
    if u is not None:
        # 设置session
        session['user_id'] = u.id
        # session永不过期
        session.permanent = True
        flash("登陆成功")
        return redirect(url_for('index'))
    else:
        flash("用户名或密码错误")
        return redirect(url_for('user.login'))


@main.route('/register')
def register():
    username = current_user_name()
    return render_template('register.html', title='register', username=username)


@main.route('/register/add', methods=['post'])
def add_user():
    User.multi_add_user()

    form = request.form
    u = User.add_new_user(form)
    if "重名" in str(u):
        flash("该用户名已经被注册")
    if "用户名或密码太短了" in str(u):
        # todo上线后把密码长度改为6位以上
        flash("请确保昵称长度在3到8位之间，以及密码长度6位以上")
    else:
        flash("注册成功")
        log("add_user", u.id, ':', u.username)
        # 自动登陆
        session['user_id'] = u.id
        # session永不过期
        session.permanent = True

        # 注册成功将之前todo的访客数据加入用户标记
        Todo.user_in_todo(u)
        return redirect(url_for('index'))
    return redirect(url_for('user.register'))


@main.route('/logout')
def logout():
    if session.get('user_id') is not None:
        p = session.pop('user_id')
        log("sign-out", p)
    return redirect(url_for('index'))


# if __name__ == '__main__':
#     print(type('是'))

routes/video.py
from flask import (
    Blueprint,
    render_template,
    abort,
)
from models.user import current_user_name
from models.video import (cyanide_videos,
                          cyanide_path,
                          others_path,
                          others_videos,
                          )


# 创建蓝图,蓝图名为main
main = Blueprint('videos', __name__)


@main.route('/')
def index():
    return render_template('video_index.html',
                           title='视频',
                           username=current_user_name(),
                           cyanide=cyanide_videos,
                           cyanide_path=cyanide_path,
                           others=others_videos,
                           others_path=others_path,
                           )


@main.route('cyanide/<name>')
def cyanide(name):
    path = [k for d in cyanide_videos for k in d]
    if name not in path:
        abort(404)
    return render_template("video.html",
                           title=name,
                           username=current_user_name(),
                           path=cyanide_path,
                           )


@main.route('others/<name>')
def others(name):
    path = [k for d in others_videos for k in d]
    if name not in path:
        abort(404)
    return render_template("video.html",
                           title=name,
                           username=current_user_name(),
                           path=others_path,
                           )

templates/all_by_yan.html
{% extends 'base2.html' %}

{% block head %}
    {{ super() }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.min.js"></script>
{% endblock %}

{% block content %}
    <table class="table table-sm">
        <thead>
        <tr>
            <th>content</th>
            <th class="fa fa-calendar">time</th>

            <th>cookie</th>
            <th>user</th>
            <th>guest</th>
        </tr>
        </thead>
        <tbody>
        {% for m in page %}
            <tr class=" {% if m.delete==true %}bg-secondary{% endif %}">
                <td>{{ m.content }}</td>
                <td class="calendar">{{ m.ct }}</td>

                <td>{{ m.cookie[-6:] }}</td>
                <td>{{ m.user }}</td>
                <td>{{ m.message_user }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


    <nav aria-label="...">
        <ul class="pagination">
            <li class="page-item disabled">
                <a class="page-link" href="#!" tabindex="-1">Previous</a>
            </li>

            {% for i in range(1, length) %}
                <li class="page-item {% if request.path.split('/')[-1]== i|string %}active{% endif %}">
                    <a class="page-link" href="{{ i }}">{{ i }}<span class="sr-only">(current)</span></a>
                </li>
            {% endfor %}


            <li class="page-item">
                <a class="page-link  {% if length-2<request.path.split('/')[-1]|int %}disabled{% endif %}" href="{{ request.path.split('/')[-1]|int + 1 }}" tabindex="-1">Next </a>
            </li>
        </ul>
    </nav>
    <div>
    <div>总共：{{ len_all }}</div>
    <div>已删：{{ len_del }}</div>
    </div>

    <script>
        var cts = document.querySelectorAll('td.calendar');
        for (var ct of cts) {
            var int_ct = ct.innerText;
            log(int_ct);
            var time = moment(parseInt(int_ct.toString() + '000')).format('YYMM.DD HH:mm:ss');
            ct.textContent = time;
        }
    </script>
{% endblock %}

templates/base2.html
{% extends "bootstrap/base.html" %}

{% block meta %}
    {{ super() }}
    <meta charset="UTF-8">
{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

{% endblock %}

{% block html_attribs %} lang="zh"{% endblock %}

{% block styles %}
    {{ super() }}

    <link rel="stylesheet" href="{{ url_for('static',filename='css/navbar.css') }}">
{% endblock %}

{% block title %}
    {% if title %}
        {{ title }} | 烟灰烬
    {% else %}
        烟灰烬
    {% endif %}
{% endblock %}


{% block navbar %}
    <nav class="navbar navbar-expand-md navbar-dark bg-info">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false"
                aria-label="Toggle navigation" style="">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/">烟灰烬</a>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-md-0">
                <li class="nav-item {% if request.endpoint == 'index' %}active{% endif %}">
                    <a class="nav-link" href="/">主页
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item {% if request.endpoint == 'videos.index' %}active{% endif %}">
                    <a class="nav-link" href={{ url_for('videos.index') }}>视频</a>
                </li>
                <li class="nav-item {% if request.endpoint == 'todo.index' %}active{% endif %}">
                    <a class="nav-link" href={{ url_for("todo.index") }}>Todo</a>
                </li>
                <li class="nav-item {% if request.endpoint == 'message.index' %}active{% endif %}">
                    <a class="nav-link" href={{ url_for('message.index') }}>聊天室</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#!">Google</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#!">文章</a>
                </li>
            </ul>
            <div class="form-inline">
                <ul class="navbar-nav mr-auto mt-2 mt-md-0">

                    {% if not username %}
                        <li class="nav-item">
                            <a id="user" class="btn btn-info" href={{ url_for('user.login') }}>登陆</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-info" href={{ url_for('user.register') }}>注册</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a id="user" class="btn btn-info font-weight-bold text"
                               href={{ url_for('user.login') }}>{{ username }}</a>
                        </li>
                        <li class="nav-item fa fa-sign-out-alt mr-2">
                            <a class="btn btn-info font-weight-bold text-warning"
                               href={{ url_for('user.logout') }}>登出</a>
                        </li>
                    {% endif %}

                </ul>
                <form class="form-inline my-2 my-lg-0" _lpchecked="1">
                    <input class="form-control mr-sm-2" type="text" placeholder="搜索">
                    <button type="button" class="btn btn-warning" data-container="body" data-toggle="popover"
                            data-placement="bottom" data-content="别点了，没用的" data-original-title="" title="">
                        Go
                    </button>
                </form>
            </div>
        </div>
    </nav>
    {% if get_flashed_messages()[0] %}
        <div class="alert alert-dismissible fade show alert-info" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <strong>{{ get_flashed_messages()[0] }}</strong>
        </div>
    {% endif %}
{% endblock %}

{% block content %}

{% endblock %}

templates/login.html
{% extends 'base2.html' %}

{% block content %}

    {% if not username %}
        <div>
            <form method="post" action={{ url_for('user.sign_in') }}>
                <input type="text" name="username" placeholder="请输入昵称">
                <input type="password" name="password" placeholder="请输入密码">
                <button>登陆</button>
            </form>
        </div>
    {% else %}
        <div class="text-center">
            <h1>你好! {{ username }}</h1>
        </div>

    {% endif %}

{% endblock %}

templates/register.html
{% extends 'base2.html' %}

{% block content %}

    <div>
        <form  method="POST" action={{ url_for("user.add_user") }}>
            <input type="text" name="username" placeholder="请输入昵称">
            <input type="password" name="password" placeholder="请输入密码">
            <button>注册</button>
        </form>
    </div>
{% endblock %}

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="edit_line">
    <span class="edit_input">5201314</span>
    <button class="edit">编辑</button>
</div>
</body>

<script>
    var id = document.querySelector("#edit_line");
    id.on("click", ".edit", function () {//点击编辑的操作（动态绑定，作用于动态生成的HTML）
    var origin = $(this).parent().find(".edit_input");//找到要修改文本的容器节点
    var text = origin.text();//保存下初始文本
    origin.remove();//移除这个节点
    var input = $("<input>");//创建一个input
    input.attr("class", "edit_input").attr("value", text);//给这个input指定class并把初始值赋给它的value
    $(this).parent().prepend(input);//插到父容器的前面
    input.focus();//把光标移动到input上
    $(this).removeClass("edit").addClass("confirm").text("确定");//修改class和button的文字
}).on("click", ".confirm", function () {//点击确定的操作
    var change = $(this).parent().find(".edit_input");//找到input的节点
    var value = change.val();//获取修改后的值
    //do some post action here!（发送一个请求保存到数据库）
    change.remove();//移除这个input
    var span = $("<span/>");//创建一个span标签
    span.attr("class", "edit_input").text(value);//修改它的class和文本内容为用户输入的内容
    $(this).parent().prepend(span);//插到父容器前面
    $(this).removeClass("confirm").addClass("edit").text("编辑");//修改class和button的文字
}).on("keyup", ".edit_input", function (e) {//输入后按回车键保存功能
    var e = e || window.event;
    if (e.keyCode == 13) {
        $("#edit_line").find(".confirm").click();//调用上面的“确定”点击事件
    }
}).on("click", "span.edit_input", function () {//直接点击文字也可以编辑
    $("#edit_line").find(".edit").click();//调用上面的“编辑”点击事件
})
$("#edit_line").on("click", ".edit", function () {//点击编辑的操作（动态绑定，作用于动态生成的HTML）
    var origin = $(this).parent().find(".edit_input");//找到要修改文本的容器节点
    var text = origin.text();//保存下初始文本
    origin.remove();//移除这个节点
    var input = $("<input>");//创建一个input
    input.attr("class", "edit_input").attr("value", text);//给这个input指定class并把初始值赋给它的value
    $(this).parent().prepend(input);//插到父容器的前面
    input.focus();//把光标移动到input上
    $(this).removeClass("edit").addClass("confirm").text("确定");//修改class和button的文字
}).on("click", ".confirm", function () {//点击确定的操作
    var change = $(this).parent().find(".edit_input");//找到input的节点
    var value = change.val();//获取修改后的值
    //do some post action here!（发送一个请求保存到数据库）
    change.remove();//移除这个input
    var span = $("<span/>");//创建一个span标签
    span.attr("class", "edit_input").text(value);//修改它的class和文本内容为用户输入的内容
    $(this).parent().prepend(span);//插到父容器前面
    $(this).removeClass("confirm").addClass("edit").text("编辑");//修改class和button的文字
}).on("keyup", ".edit_input", function (e) {//输入后按回车键保存功能
    var e = e || window.event;
    if (e.keyCode == 13) {
        $("#edit_line").find(".confirm").click();//调用上面的“确定”点击事件
    }
}).on("click", "span.edit_input", function () {//直接点击文字也可以编辑
    $("#edit_line").find(".edit").click();//调用上面的“编辑”点击事件
})
</script>
</html>

templates/todo.html
{% extends "base2.html" %}


{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="/static/css/myvideo.css">

    <!--ajax-->
{#    <script src="/static/js/ajax.js"></script>#}
{% endblock %}


{% block content %}


    <div class="center">
        <img class="img-50" src="/static/todo.jpg">
        <footer class="blockquote-footer">Do anything
            <cite title="Don't think too much">you want</cite>
        </footer>
    </div>
    <div class="card-body mt-2 center">
        <form class="block-center" action={{ url_for("todo.add") }} method="post"> {# method="post" #}
            <input type="text" class="form-control" placeholder="let's do something" aria-label=""
                   aria-describedby="basic-addon1"
                   name="title">
            <input id="submit" class="btn btn-success border-left" type="button" value="Do it!">
        </form>
    </div>
    <div>
        <table class="table table-hover table-striped">
            <thead class="thead-dark">
            <tr class="text-center">
                <th> #</th>
                <th> Title</th>
                <th> Time</th>
                <th> Action</th>
            </tr>
            </thead>
            <tbody class="text-center">
            {% for t in todos %}
                <tr class="table-warning">
                    <td class="d-none">{{ t.id }}</td>
                    <td scope="row">{{ loop.index }}</td>
                    <td>{{ t.title }}</td>
                    <td>{{ t.ct }}</td>
                    <td><a id="todo-{{ t.id }}" class="btn btn-danger"
{#                            href={{ url_for("todo.delete", todo_id=t.id) }}>delete</a></td>#}
                            href='#'>delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    <script src="/static/js/ajax.js"></script>
{% endblock %}